"""add tables to database

Revision ID: 32ad5a9573d8
Revises: a7f3d9c2b1e4
Create Date: 2026-04-17 21:30:33.046693

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '32ad5a9573d8'
down_revision: Union[str, None] = 'a7f3d9c2b1e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###