"""remove rating from products

Revision ID: a8783efef0b9
Revises: 27c35900f25b
Create Date: 2026-01-27 09:17:38.483252

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8783efef0b9'
down_revision: Union[str, None] = '27c35900f25b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('orders_user_id_fkey'), 'orders', type_='foreignkey')
    op.create_foreign_key(None, 'orders', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('products', 'rating')
    op.drop_constraint(op.f('reviews_user_id_fkey'), 'reviews', type_='foreignkey')
    op.create_foreign_key(None, 'reviews', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'reviews', type_='foreignkey')
    op.create_foreign_key(op.f('reviews_user_id_fkey'), 'reviews', 'users', ['user_id'], ['id'])
    op.add_column('products', sa.Column('rating', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.create_foreign_key(op.f('orders_user_id_fkey'), 'orders', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###